### ISSUE TITLE
Disable drag to move polygon while editing.

### ISSUE THREAD

**Issue by jolyonralph** [mapbox/geojson.io#565]
It is HUGELY annoying when editing points on a complex polygon when I accidentally miss one point and instead start to move the entire polygon around.   I can't think of a single time, ever, that I'd want to move a polygon around the map compared to the times I'd want it to stay exactly where it is. 

Can we please, please, please have an option to disable the ability to drag polygons around while editing. I want to manipulate the points, nothing else.

Thank you :)

**Comment by jolyonralph** [comment]
Please? Anyone? This is driving me crazy.

**Comment by jolyonralph** [comment]
Keeps happening. Still infuriating.

Is this project still supported? Just curious.  Are there any alternatives?

**Comment by tomscholz** [comment]
I implemented this feature, but I don't see any way to do, what you are looking for. You could clone the repo and remove the feature, If you don't need the moving feature.

**Comment by jolyonralph** [comment]
Can we PLEASE at least have an option to UNDO a move?  

Honestly, adding this feature without having a way to disable or undo it was pretty reckless.

**Comment by thisislawatts** [comment]
Hey @jolyonralph, you could try out a site like scribblemaps.com they have a pretty sophisticated editing tool and the free version should do most things you need. Although their paid plan is pretty reasonable if you're not looking to make a PR on this repo to implement the features you're after.

**Comment by jolyonralph** [comment]
Thanks, I will check this out. 

Although I am frustrated because geojson.io does everything that I need perfectly *except* this awful move issue which has cost me countless time.

I would not be opposed to paying someone here to fix this bug/"feature" if the price was fair.

**Comment by jolyonralph** [comment]
Unfortunately scribblemaps.com isn't appropriate. I'm trying to encourage people within our community (http://www.mindat.org) to generate geojson maps of areas of geological/mineralogical interest (eg mining districts.)   I can't ask everyone to pay $99 a year for that.  But I don't mind paying a little for someone to add the required option to disable drag-to-move here.

**Comment by jolyonralph** [comment]
ps. my preferred solution to this issue looking at how the UI is currently built is to change the system so that to drag an existing polygon around a map you need to hold shift while dragging with the mouse.

**Comment by tomscholz** [comment]
Shift is already in use to zoom

**Comment by thisislawatts** [comment]
I believe that scribblemaps might have a package which allows you to use it as part of a service, but understand your point. I ultimately switched to using geojson.io because of it's focused feature set.

I agree that undo functionality could be useful but perhaps that's worth splitting out to a separate thread as it's likely a non trivial feature to implement.

Currently the draggable markers are only 8&times;8px, so definitely a bit on the dainty side for people to click. We could add a :before pseudo element to the markers to make them a little easier to aim for:

__Gif demonstrating markers with larger hit targets__ 

![geojsondraggablemarkers](https://cloud.githubusercontent.com/assets/472589/26025228/d1cebf86-37da-11e7-82c4-0a2f45e0c4be.gif)

__Gif demonstrating larger hit targets and :hover styling to emphasis active marker__  

![geojsondraggablemarkerswithoutlines](https://cloud.githubusercontent.com/assets/472589/26025293/38eac858-37dc-11e7-8cc0-8d7f307667d6.gif)

What do you think of this approach? Could be as simple as the following CSS tweaks, although ideally would look at issuing PR upstream to Leaflet.draw.drag to improve things.

```css
.leaflet-editing-icon:before {
    content: "";
    display: block;
    width: 525%;
    height: 525%;
    /* background: lime; */
    me; */
    z-index: 2;
    position: relative;
    margin-left: -220%;
    margin-top: -220%;
}
/*
  Oh dear use of !important, currently :hover styles are being applied via JS.
  This could be done better.
*/
.leaflet-editing-icon:hover {
    border: 2px hsla(349, 53%, 13%, 1) solid;
    height: 10px !important;
    width: 10px !important;
    margin-top: -5px !important;
    margin-left: -5px !important;
    border-radius: 5px;
}
```
